// AETHER AG — Complete Seeded Demo Data (Asha's Farm, Maharashtra, India)
import type {
  FarmTwin, Field, CropCycle, StreamCard, ResolutionCard,
  DroneMission, IrrigationAction, WeatherForecast, HarvestScenario,
  OutcomeVerification, TimelineEvent, YieldOutlook, ClimateRisk,
  CropDiagnosis, SatelliteObservation, ResearchExperiment, CountryPack
} from '@/types';

export const DEMO_COUNTRY_PACKS: CountryPack[] = [
  { code: 'IN', name: 'India', flag: '🇮🇳', currency: 'INR', areaUnit: 'hectares', weightUnit: 'kg', temperatureUnit: 'C', language: 'English / Hindi', cropCalendar: ['Kharif', 'Rabi', 'Zaid'], marketConnectors: ['Agmarknet', 'eNAM', 'APMC'], weatherSource: 'IMD / Open-Meteo', agronomicReferences: ['ICAR', 'KVK', 'State Agriculture Dept'], demoFarmer: 'Asha', demoRegion: 'Maharashtra' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', currency: 'KES', areaUnit: 'acres', weightUnit: 'kg', temperatureUnit: 'C', language: 'English / Swahili', cropCalendar: ['Long Rains', 'Short Rains'], marketConnectors: ['Twiga Foods', 'Farmers Market'], weatherSource: 'Open-Meteo', agronomicReferences: ['KALRO', 'Ministry of Agriculture'], demoFarmer: 'Amina', demoRegion: 'Nakuru County' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', currency: 'EUR', areaUnit: 'hectares', weightUnit: 'kg', temperatureUnit: 'C', language: 'Spanish', cropCalendar: ['Spring', 'Summer', 'Autumn'], marketConnectors: ['Mercabarna', 'Lonja'], weatherSource: 'AEMET / Open-Meteo', agronomicReferences: ['INIA', 'CCAA'], demoFarmer: 'Carlos', demoRegion: 'Andalucía' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', currency: 'BRL', areaUnit: 'hectares', weightUnit: 'kg', temperatureUnit: 'C', language: 'Portuguese', cropCalendar: ['Safra', 'Safrinha'], marketConnectors: ['CEPEA', 'B3 Agro'], weatherSource: 'INMET / Open-Meteo', agronomicReferences: ['Embrapa', 'MAPA'], demoFarmer: 'Fernanda', demoRegion: 'Mato Grosso' },
  { code: 'US', name: 'United States', flag: '🇺🇸', currency: 'USD', areaUnit: 'acres', weightUnit: 'lbs', temperatureUnit: 'F', language: 'English', cropCalendar: ['Spring', 'Summer', 'Fall'], marketConnectors: ['CME Group', 'USDA AMS'], weatherSource: 'NOAA / Open-Meteo', agronomicReferences: ['USDA', 'Extension Services'], demoFarmer: 'John', demoRegion: 'Iowa' },
];

export const DEMO_FARM_TWIN: FarmTwin = {
  id: 'farm-asha-001',
  farmId: 'farm-asha-001',
  farmerName: 'Asha Pawar',
  country: 'India',
  region: 'Nashik, Maharashtra',
  farmName: 'Aether Green Farm',
  farmSizeHectares: 2,
  farmMode: 'small_plot',
  countryCode: 'IN',
  fields: [
    {
      id: 'field-north',
      farmId: 'farm-asha-001',
      name: 'North Field',
      areaHectares: 1.2,
      boundary: { type: 'Polygon', coordinates: [[[73.780, 20.010], [73.790, 20.010], [73.790, 20.018], [73.780, 20.018], [73.780, 20.010]]] },
      centroid: { lat: 20.014, lng: 73.785 },
      soilCharacteristics: { type: 'loam', ph: 6.5, organicMatter: 2.1, nitrogen: 0.18, phosphorus: 24, potassium: 180, waterRetention: 'medium' },
      irrigationMethod: 'drip',
      waterSource: 'borewell',
      currentCropCycleId: 'cycle-tomato-001',
    },
    {
      id: 'field-south',
      farmId: 'farm-asha-001',
      name: 'South Field',
      areaHectares: 0.8,
      boundary: { type: 'Polygon', coordinates: [[[73.780, 20.000], [73.790, 20.000], [73.790, 20.008], [73.780, 20.008], [73.780, 20.000]]] },
      centroid: { lat: 20.004, lng: 73.785 },
      soilCharacteristics: { type: 'clay', ph: 6.8, organicMatter: 1.8, nitrogen: 0.15, phosphorus: 20, potassium: 160, waterRetention: 'high' },
      irrigationMethod: 'sprinkler',
      waterSource: 'borewell',
    },
  ],
  cropCycles: [
    {
      id: 'cycle-tomato-001',
      fieldId: 'field-north',
      farmId: 'farm-asha-001',
      cropName: 'Tomato',
      cropVariety: 'Arka Rakshak',
      sowingDate: '2026-05-10',
      expectedHarvestDate: '2026-08-15',
      cropStage: 'flowering',
      estimatedYieldTons: 28,
      inputCostPerHectare: 45000,
      notes: 'Good germination. Flowering stage reached on schedule.',
    },
  ],
  historicalYield: [
    { year: 2023, fieldId: 'field-north', cropName: 'Tomato', yieldTons: 24, salePrice: 18, netRevenue: 187200 },
    { year: 2024, fieldId: 'field-north', cropName: 'Onion', yieldTons: 18, salePrice: 22, netRevenue: 144000 },
    { year: 2025, fieldId: 'field-north', cropName: 'Tomato', yieldTons: 26, salePrice: 21, netRevenue: 252000 },
  ],
  pestIncidents: [
    { id: 'pest-001', fieldId: 'field-north', date: '2025-07-12', type: 'disease', name: 'Early Blight (Alternaria solani)', severity: 'medium', treatmentApplied: 'Mancozeb 75 WP', outcome: 'Controlled within 10 days' },
  ],
  treatments: [
    { id: 'treat-001', fieldId: 'field-north', date: '2026-06-15', type: 'fertilizer', product: 'NPK 19-19-19', quantity: 5, unit: 'kg', appliedBy: 'Asha' },
    { id: 'treat-002', fieldId: 'field-north', date: '2026-07-01', type: 'fertilizer', product: 'Calcium Nitrate', quantity: 3, unit: 'kg', appliedBy: 'Asha' },
  ],
  observations: [
    { id: 'obs-001', farmId: 'farm-asha-001', fieldId: 'field-north', type: 'satellite', timestamp: '2026-07-10T06:00:00Z', ndviValue: 0.61, stressLevel: 'low', notes: 'Mild stress detected in north-east quadrant', dataSource: 'simulated' },
    { id: 'obs-002', farmId: 'farm-asha-001', fieldId: 'field-north', type: 'drone', timestamp: '2026-07-09T08:30:00Z', ndviValue: 0.58, stressLevel: 'medium', notes: 'Localised yellowing near row 7-9. Possible early fungal onset.', dataSource: 'simulated' },
  ],
  activityTimeline: [
    { id: 'evt-001', farmId: 'farm-asha-001', fieldId: 'field-north', timestamp: '2026-07-11T06:00:00Z', type: 'weather_event', title: 'Humidity spike detected', description: 'Relative humidity exceeded 85% for 6 consecutive hours', dataSource: 'simulated' },
    { id: 'evt-002', farmId: 'farm-asha-001', fieldId: 'field-north', timestamp: '2026-07-10T14:00:00Z', type: 'observation', title: 'Satellite observation', description: 'NDVI: 0.61. Mild vegetation stress in NE quadrant.', dataSource: 'simulated' },
    { id: 'evt-003', farmId: 'farm-asha-001', timestamp: '2026-07-01T09:00:00Z', type: 'treatment', title: 'Calcium Nitrate applied', description: '3kg Calcium Nitrate applied to North Field', dataSource: 'live' },
  ],
  lastUpdated: new Date().toISOString(),
  dataQualityScore: 82,
};

export const DEMO_STREAM_CARDS: StreamCard[] = [
  {
    id: 'card-001',
    priority: 'critical',
    type: 'weather',
    title: 'Fungal Risk Alert',
    subtitle: 'High humidity + rainfall predicted within 18 hours — tomato flowering stage at risk',
    fieldName: 'North Field',
    predictedTime: 'Next 18 hours',
    financialImpact: '₹18,000–₹32,000 crop value at risk',
    confidence: 87,
    dataSources: ['Open-Meteo forecast', 'Humidity sensor', 'Crop stage: Flowering'],
    dataSource: 'simulated',
    resolutionCardId: 'res-001',
    actionLabel: 'Apply Resolution',
    dismissed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'card-002',
    priority: 'high',
    type: 'irrigation',
    title: 'Pause Irrigation Recommended',
    subtitle: 'Soil moisture in North Field is above optimal. Rain expected. Irrigation would cause waterlogging.',
    fieldName: 'North Field',
    predictedTime: 'Act within 2 hours',
    financialImpact: 'Save ₹420 in water cost + protect roots',
    confidence: 92,
    dataSources: ['Soil moisture model', 'Rain forecast', 'Field history'],
    dataSource: 'simulated',
    resolutionCardId: 'res-002',
    actionLabel: 'Pause Irrigation',
    dismissed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'card-003',
    priority: 'medium',
    type: 'market',
    title: 'Harvest Window Opportunity',
    subtitle: 'Tomato prices rising 12% in Nashik APMC. Optimal harvest window opens in 5–8 days.',
    fieldName: 'North Field',
    predictedTime: '5–8 days',
    financialImpact: 'Est. additional ₹14,000 if timed correctly',
    confidence: 74,
    dataSources: ['Simulated APMC price data', 'Crop maturity model', 'Weather forecast'],
    dataSource: 'simulated',
    resolutionCardId: 'res-003',
    actionLabel: 'Compare Scenarios',
    dismissed: false,
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_RESOLUTION_CARDS: Record<string, ResolutionCard> = {
  'res-001': {
    id: 'res-001',
    farmId: 'farm-asha-001',
    fieldId: 'field-north',
    priority: 'critical',
    title: 'Fungal Disease Prevention',
    detected: 'Relative humidity has been above 85% for 6 hours. Open-Meteo forecasts 34mm rainfall within 18 hours. North Field tomatoes are at flowering stage — the most vulnerable period for fungal infection (Alternaria, Phytophthora, Botrytis).',
    mayHappen: 'If no action is taken, fungal spores will propagate rapidly in humid conditions. Flowering-stage infection can cause 40–70% yield loss within 7–10 days.',
    recommendation: 'Apply a preventive copper-based fungicide spray before rainfall arrives. Ensure adequate canopy airflow. Do not irrigate in the next 36 hours.',
    why: 'Copper-based fungicides create a protective barrier on leaf surfaces before fungal spores establish. Flowering-stage intervention is significantly more effective than post-infection treatment. Historical farm data shows this combination reduced fungal spread by 68% in the 2025 cycle.',
    whenToAct: 'Within the next 4 hours — before humidity increases further and wind speed drops (which occurs at sundown)',
    expectedBenefit: 'Protect an estimated 18–28 tons of tomato yield worth ₹3.6–5.6 lakhs',
    estimatedCost: '₹800–1,200 for copper hydroxide spray application',
    riskOfDelay: 'Each 6-hour delay increases fungal establishment probability by ~22%. Once established, treatment cost rises 4–6x and yield loss becomes harder to reverse.',
    confidence: 87,
    dataSources: ['Open-Meteo 7-day forecast', 'Farm humidity log', 'ICAR crop disease calendar', 'Historical farm twin data'],
    dataSource: 'simulated',
    alternatives: ['Apply neem oil (organic) — effective but slower acting', 'Increase canopy ventilation only — lower effectiveness', 'Wait and monitor — not recommended given confidence level'],
    requiresApproval: true,
    followUpVerification: 'Photograph tomato canopy after 48 hours. Aether will compare with current observation.',
    actionType: 'record_treatment',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  'res-002': {
    id: 'res-002',
    farmId: 'farm-asha-001',
    fieldId: 'field-north',
    priority: 'high',
    title: 'Pause Scheduled Irrigation',
    detected: 'North Field soil moisture is at 78% field capacity — above the optimal 65% for tomatoes at flowering stage. Rainfall of 34mm is forecast within 18 hours.',
    mayHappen: 'Running scheduled irrigation will push soil moisture to saturation. Combined with expected rainfall, this creates waterlogging risk, which damages roots and worsens fungal conditions.',
    recommendation: 'Pause the scheduled irrigation cycle for North Field for at least 48 hours. Resume when soil moisture drops below 60% or rainfall is confirmed to be less than 20mm.',
    why: 'Tomato roots are particularly sensitive to oxygen deprivation from waterlogged soil during flowering. Root stress at this stage directly reduces fruit set percentage.',
    whenToAct: 'Immediately — the scheduled irrigation is due in 45 minutes',
    expectedBenefit: 'Prevent root stress, save 2,400 litres of water, reduce pumping cost by ₹420',
    estimatedCost: 'No cost — this is a pause action',
    riskOfDelay: 'Irrigation activation in current soil conditions will waste water and risk root zone saturation',
    confidence: 92,
    dataSources: ['Soil moisture model', 'Open-Meteo rain forecast', 'Irrigation schedule log', 'Field capacity data'],
    dataSource: 'simulated',
    alternatives: ['Reduce irrigation to 30% of scheduled volume', 'Proceed with irrigation and open drainage — higher risk'],
    requiresApproval: true,
    followUpVerification: 'Check soil moisture reading after rainfall event. Aether will recommend next irrigation window.',
    actionType: 'pause_irrigation',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  'res-003': {
    id: 'res-003',
    farmId: 'farm-asha-001',
    fieldId: 'field-north',
    priority: 'medium',
    title: 'Review Harvest Window',
    detected: 'Tomato prices in Nashik APMC have risen 12% over 5 days. Crop maturity model estimates fruit readiness in 5–9 days. Post-harvest weather shows stable conditions.',
    mayHappen: 'Tomato prices are cyclical. A competitor supply surge from Pune is likely in 12–14 days, which may depress prices by 18–25%.',
    recommendation: 'Plan harvest for day 5–7 window. Compare cooperative vs direct market options.',
    why: 'Early harvest at rising prices captures better margin. Cooperative channel offers better logistics for your farm size.',
    whenToAct: 'Review now, plan harvest team for 5 days from today',
    expectedBenefit: 'Est. ₹12,000–18,000 additional revenue vs waiting',
    estimatedCost: 'Harvest labour: ₹4,500 for 2-day harvest',
    riskOfDelay: 'Prices likely to soften in 10–12 days. Fruit quality peaks at optimal ripeness — overripe tomatoes attract 15–20% price penalty.',
    confidence: 74,
    dataSources: ['Simulated APMC price dataset', 'Crop maturity model', 'Weather forecast', 'Historical price patterns'],
    dataSource: 'simulated',
    alternatives: ['Sell through cooperative (+₹2/kg premium, 3-day delay)', 'Explore export grade sorting (+₹5/kg for A-grade)'],
    requiresApproval: false,
    followUpVerification: 'Record actual harvest yield and sale price. Aether will update Farm Twin and price model.',
    actionType: 'harvest_window',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
};

export const DEMO_YIELD_OUTLOOK: YieldOutlook = {
  currentOutlook: 'good',
  yieldRangeLow: 24,
  yieldRangeHigh: 31,
  unit: 'tons/hectare',
  confidence: 78,
  mainLimitingFactor: 'Emerging fungal pressure at flowering stage',
  recommendedIntervention: 'Apply preventive copper fungicide within 4 hours',
  estimatedValueProtectedINR: 280000,
  dataQualityIndicator: 'medium',
  dataSource: 'simulated',
};

export const DEMO_CLIMATE_RISKS: ClimateRisk[] = [
  { id: 'risk-001', farmId: 'farm-asha-001', fieldId: 'field-north', riskType: 'fungal', riskLevel: 'critical', title: 'Fungal Disease Outbreak Risk', description: 'Humidity above 85% combined with forecast rainfall creates ideal fungal spore germination conditions for flowering-stage tomatoes.', affectedTimeWindow: 'Next 18–36 hours', reason: 'Relative humidity: 87%. Rain forecast: 34mm. Crop stage: Flowering (highest vulnerability). Night temperature: 24°C (optimal for Phytophthora)', confidence: 87, recommendedAction: 'Apply copper-based preventive fungicide within 4 hours', consequenceOfDelay: 'Fungal establishment probability increases ~22% per 6-hour delay', dataSource: 'simulated', createdAt: new Date().toISOString() },
  { id: 'risk-002', farmId: 'farm-asha-001', fieldId: 'field-north', riskType: 'waterlogging', riskLevel: 'high', title: 'Waterlogging Risk — North Field', description: 'Soil moisture at 78% field capacity. 34mm rainfall forecast. Current irrigation schedule would oversaturate root zone.', affectedTimeWindow: 'Next 12–24 hours', reason: 'Clay-loam mix with high current moisture + heavy rain = waterlogging risk', confidence: 92, recommendedAction: 'Pause irrigation immediately. Open drainage channel.', consequenceOfDelay: 'Root oxygen deprivation causes irreversible fruit set reduction', dataSource: 'simulated', createdAt: new Date().toISOString() },
  { id: 'risk-003', farmId: 'farm-asha-001', fieldId: 'field-north', riskType: 'wind', riskLevel: 'medium', title: 'Wind Advisory — Foliar Spraying', description: 'Wind speed forecast to reach 28 km/h tomorrow afternoon. Foliar applications in this wind will have 40–60% drift loss.', affectedTimeWindow: 'Tomorrow 14:00–18:00', reason: 'Wind forecast: 28 km/h. Optimal spraying: <15 km/h', confidence: 81, recommendedAction: 'Schedule foliar spray for early morning (06:00–09:00)', consequenceOfDelay: 'Wasted chemical cost, ineffective application, potential off-target contamination', dataSource: 'simulated', createdAt: new Date().toISOString() },
];

export const DEMO_DRONE_MISSION: DroneMission = {
  id: 'drone-mission-001',
  farmId: 'farm-asha-001',
  fieldId: 'field-north',
  missionType: 'inspection',
  status: 'idle',
  scheduledAt: new Date().toISOString(),
  flightPath: [
    { lat: 20.010, lng: 73.780 }, { lat: 20.010, lng: 73.785 }, { lat: 20.010, lng: 73.790 },
    { lat: 20.013, lng: 73.790 }, { lat: 20.013, lng: 73.785 }, { lat: 20.013, lng: 73.780 },
    { lat: 20.016, lng: 73.780 }, { lat: 20.016, lng: 73.785 }, { lat: 20.016, lng: 73.790 },
    { lat: 20.018, lng: 73.790 }, { lat: 20.018, lng: 73.785 }, { lat: 20.018, lng: 73.780 },
  ],
  altitudeMeters: 30,
  coveragePercent: 0,
  batteryStart: 94,
  observations: [],
  dataSource: 'simulated',
  weatherSuitable: true,
  pilotNote: 'Simulated drone telemetry for prototype demonstration.',
};

export const DEMO_HARVEST_SCENARIOS: HarvestScenario[] = [
  { id: 'h-now', farmId: 'farm-asha-001', cropCycleId: 'cycle-tomato-001', label: 'Harvest Now', harvestDate: new Date().toISOString(), estimatedYieldTons: 22, estimatedPricePerKg: 19, estimatedGrossRevenue: 418000, logisticsCost: 12000, storageCost: 0, estimatedNetRevenue: 406000, weatherRisk: 'low', marketOpportunity: 'Below peak — market still climbing', confidence: 85, recommended: false, dataSource: 'simulated' },
  { id: 'h-3days', farmId: 'farm-asha-001', cropCycleId: 'cycle-tomato-001', label: 'Wait 3 Days', harvestDate: new Date(Date.now() + 3 * 86400000).toISOString(), estimatedYieldTons: 25, estimatedPricePerKg: 22, estimatedGrossRevenue: 550000, logisticsCost: 12000, storageCost: 0, estimatedNetRevenue: 538000, weatherRisk: 'medium', marketOpportunity: 'Near peak price window', confidence: 74, recommended: false, dataSource: 'simulated' },
  { id: 'h-7days', farmId: 'farm-asha-001', cropCycleId: 'cycle-tomato-001', label: 'Wait 7 Days', harvestDate: new Date(Date.now() + 7 * 86400000).toISOString(), estimatedYieldTons: 27, estimatedPricePerKg: 18, estimatedGrossRevenue: 486000, logisticsCost: 12000, storageCost: 0, estimatedNetRevenue: 474000, weatherRisk: 'high', marketOpportunity: 'Competitor supply surge likely', confidence: 61, recommended: false, dataSource: 'simulated' },
  { id: 'h-coop', farmId: 'farm-asha-001', cropCycleId: 'cycle-tomato-001', label: 'Cooperative (+3 days)', harvestDate: new Date(Date.now() + 4 * 86400000).toISOString(), estimatedYieldTons: 25, estimatedPricePerKg: 24, estimatedGrossRevenue: 600000, logisticsCost: 6000, storageCost: 0, estimatedNetRevenue: 594000, weatherRisk: 'medium', marketOpportunity: 'Premium cooperative pricing + logistics support', confidence: 79, recommended: true, dataSource: 'simulated' },
  { id: 'h-store', farmId: 'farm-asha-001', cropCycleId: 'cycle-tomato-001', label: 'Harvest + Store 5 Days', harvestDate: new Date(Date.now() + 2 * 86400000).toISOString(), estimatedYieldTons: 24, estimatedPricePerKg: 21, estimatedGrossRevenue: 504000, logisticsCost: 12000, storageCost: 18000, estimatedNetRevenue: 474000, weatherRisk: 'low', marketOpportunity: 'Storage risk with perishable crop', confidence: 68, recommended: false, dataSource: 'simulated' },
];

export const DEMO_DIAGNOSIS: CropDiagnosis = {
  id: 'diag-001',
  farmId: 'farm-asha-001',
  fieldId: 'field-north',
  imageUrl: '/placeholder-leaf.jpg',
  mostLikelyIssue: 'Early Blight (Alternaria solani)',
  alternativePossibilities: ['Septoria Leaf Spot', 'Bacterial Speck', 'Calcium deficiency (Blossom End Rot precursor)'],
  confidence: 78,
  visibleIndicators: ['Concentric dark brown rings on lower leaves', 'Yellow halo surrounding lesions', 'Progressive defoliation from bottom upward', 'Lesions approximately 1–3cm diameter'],
  severity: 'medium',
  urgency: 'soon',
  questionsForAccuracy: ['How long have you noticed these marks?', 'Are the upper leaves also affected?', 'Have you applied fungicide in the last 14 days?'],
  immediateAction: 'Remove and destroy the 3–5 most severely affected lower leaves. Do not compost. Apply copper-based fungicide to all plants within 24 hours.',
  organicOptions: ['Copper hydroxide spray (certified organic formulation)', 'Neem oil + baking soda solution (apply weekly)', 'Trichoderma-based biocontrol agent'],
  chemicalCategory: 'Protectant fungicide — Mancozeb or Chlorothalonil (consult local agronomist for dosage per state regulations)',
  preventionAdvice: 'Increase row spacing to improve air circulation. Use mulch to prevent soil splash. Avoid overhead irrigation during humid periods.',
  followUpDays: 5,
  requiresExpert: false,
  dataSource: 'simulated',
  timestamp: new Date().toISOString(),
};

export const DEMO_RESEARCH_EXPERIMENT: ResearchExperiment = {
  id: 'exp-001',
  name: 'Acoustic Levitation Seed Lab',
  type: 'acoustic_levitation',
  status: 'running',
  frequencyKhz: 40.2,
  pressurePa: 1820,
  seedMassGrams: 0.12,
  stabilityPercent: 96.4,
  nutrientDistribution: 88.7,
  exposureDurationSec: 142,
  temperature: 24.1,
  humidity: 52.3,
  dataSource: 'simulated',
  disclaimer: 'Research prototype. Not a commercially deployed farm-control system. All telemetry is simulated for demonstration purposes.',
};
